#!/bin/bash
#
# References
# http://serverfault.com/questions/683605/docker-container-time-timezone-will-not-reflect-changes
# http://mirrors.aliyun.com/help/centos
# http://mirrors.aliyun.com/help/epel
# 

set -x
set -e

docker run --name centos-base-test \
    -it --rm \
    -v $(pwd):/share \
    centos:7.2.1511 \
    /bin/bash
